# Generated by Django 5.0.3 on 2024-03-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
